export { default as Header } from "./Header";
export { default as Navbar } from "./Navbar";
export { default as Card } from "./Card";
export { default as WatchlistCard } from "./WatchlistCard";
export { default as CustomPagination } from "./Pagination";
export { default as Genres } from "./Genres";
export { default as ContentModal } from "./Modal";
export { default as Carousel } from "./Carousel";
export { default as MovieControls } from "./MovieControls";
